# Generated by Django 2.2.1 on 2019-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('full_name_owner', models.CharField(max_length=255)),
                ('year_of_issue', models.DateField()),
            ],
        ),
    ]
